#!/bin/sh

apk add re2c alpine-sdk php5-dev autoconf imagemagick-dev libtool zlib-dev pcre-dev openssl-dev imagemagick

PHP_VERSION=$(php -r "print PHP_VERSION;")

pecl_install ()
{
  local EXT_TYPE=$1
  local NAME=$2
  local VERSION=$3
  local CONFIGURE_ARGS=$(shift 3; echo $@)
  local PECL_URL="https://pecl.php.net/get/$NAME-$VERSION.tgz"

  cd /tmp
  wget $PECL_URL
  tar xzf $NAME-$VERSION.tgz || true
  cd /tmp/$NAME-$VERSION
  phpize
  ./configure $CONFIGURE_ARGS
  make
  make install
  echo "$EXT_TYPE=$NAME.so" >> /etc/php5/conf.d/$NAME.ini
}

# Install PHP extensions from PECL

pecl_install extension mongodb 1.1.8
pecl_install extension imagick 3.4.3RC1
pecl_install zend_extension xdebug 2.4.1 --enable-xdebug

# Install GNU libiconv

mkdir -p /opt
cd /opt
wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz
tar xzf libiconv-1.14.tar.gz
cd libiconv-1.14
sed -i 's/_GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");/#if HAVE_RAW_DECL_GETS\n_GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");\n#endif/g' srclib/stdio.in.h
./configure --prefix=/usr/local
make
make install

# Download PHP source

mkdir -p /opt
cd /opt
wget http://php.net/distributions/php-$PHP_VERSION.tar.gz
tar xzf php-$PHP_VERSION.tar.gz

# Install PHP iconv from source

cd /opt/php-$PHP_VERSION/ext/iconv
phpize
./configure --with-iconv=/usr/local
make
make install
echo "extension=iconv.so" >> /etc/php5/conf.d/iconv.ini

# Cleanup

rm -rf /tmp/*
apk del re2c alpine-sdk php5-dev autoconf imagemagick-dev libtool zlib-dev pcre-dev openssl-dev