#!/bin/bash

USERNAME="user-$1"

echo "Checking $USERNAME"

umask 0002

if getent passwd $USERNAME > /dev/null 2>&1; then
	echo "user $USERNAME already exist"
else
	echo "creating user $USERNAME"
	adduser -u $1 -D -S -G www-data $USERNAME
fi

su-exec $USERNAME:www-data bash